#!/bin/sh -ex
PKGURL=$1
TARGET=$2
HOST=$3
SVNPATH=$4
NEWPATH=$5

OPTS="-essh -ar"

if [ -n "$HOST" ]; then
    # copy using rsync
    #FIXME it doesn't work, as rsync doesn't accept remote paths in both
    # source and dest
    DIR=`mktemp -td repsys.XXXXXX`
    mkdir -p ${DIR}${NEWPATH}
    (cd ${DIR}; rsync -r . ${HOST}:/)
    rsync ${OPTS} ${TARGET} ${HOST}:${NEWPATH}
    echo rm -rd ${DIR} >&2
else
    mkdir -p ${NEWPATH}
    cp -rf ${SVNPATH} ${NEWPATH}
fi
