#!/bin/sh -ex
LPATH=$1
TARGET=$2
HOST=$3
RPATH=$4
OPTS="-ar"

if [ -n "${HOST}" ]; then
    OPTS="${OPTS} -essh"
    DIR=`mktemp -d`
    mkdir -p ${DIR}${RPATH}
    (cd $DIR;
    rsync -ar ${OPTS} . ${HOST}:/)
else
    mkdir -p ${RPATH}
fi

rsync ${OPTS} ${LPATH} ${TARGET}

rm -rf ${DIR}
